version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
      actions-major:
        update-types:
        - "major"
- package-ecosystem: "gradle"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    androidx:
      patterns:
      - "androidx.*"
      - "com.google.android.material:*"
    jetbrains-kotlin:
      patterns:
      - "org.jetbrains.kotlin*"
      - "org.jetbrains.kotlinx:*"
  ignore:
    - dependency-name: "io.hammerhead:karoo-ext"
