version: 2
registries:
  hammerheadnav:
    type: maven-repository
    url: https://maven.pkg.github.com/hammerheadnav/karoo-ext
    username: x-access-token
    password: ${{ secrets.GITHUB_TOKEN }}
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
      actions-major:
        update-types:
        - "major"
- package-ecosystem: "gradle"
  directory: "/"
  registries:
    - hammerheadnav
  schedule:
    interval: "monthly"
  groups:
    androidx:
      patterns:
      - "androidx.*"
      - "com.google.android.material:*"
    jetbrains-kotlin:
      patterns:
      - "org.jetbrains.kotlin*"
      - "org.jetbrains.kotlinx:*"
